### ISSUE TITLE
Take over the original PyPI project?

### ISSUE THREAD

**Issue by mgorny** [faust-streaming/cChardet#32]
Since the original `cchardet` project is clearly no longer maintained, have you tried contacting the original author to give you permissions to take the PyPI project? And if that failed, applying for [PEP 541](https://peps.python.org/pep-0541/) name reuse?

Creating a fork has the problem that some packages will now require `cchardet` and some will require `faust-cchardet`, and both can't be installed simultaneously which causes major problems for distributions.

**Comment by wbarnha** [comment]
I have reached out to the original author a long time ago but with no response. I forgot about PEP 541, thank you for bringing this to my attention. I will submit an application.

Edit: It seems after reading the requirements for reachability:

> [Reachability](https://peps.python.org/pep-0541/#reachability)
> 
> The user of the Package Index is solely responsible for being reachable by the Package Index maintainers for matters concerning projects that the user owns. In every case where contacting the user is necessary, the maintainers will try to do so at least three times, using the following means of contact:
> 
>     the e-mail address on file in the user’s profile on the Package Index;
>     the e-mail address listed in the Author field for a given project uploaded to the Index; and
>     any e-mail addresses found in the given project’s documentation on the Index or on the listed Home Page.
> 
> The maintainers stop trying to reach the user after six weeks.

It seems I need to reach out to PyYoshi a few more times before the owner is considered "unreachable".

**Comment by mgorny** [comment]
Thanks.

I'm not sure if *you* are actually supposed to do that, and not the person handling your request. After all, how can PyPI admins know that you've actually contacted them?

I think filing a bug on their GitHub would also be a good step, as that is publicly visible.

**Comment by wbarnha** [comment]
> Thanks.
> 
> I'm not sure if _you_ are actually supposed to do that, and not the person handling your request. After all, how can PyPI admins know that you've actually contacted them?

I would forward emails to PyPi admins as evidence.

> I think filing a bug on their GitHub would also be a good step, as that is publicly visible.

Agreed, I don't like the idea of invoking PEP 541, but it seems that this project is in need of it. Opening up an issue in advance would be morally right.

Edit: Sorry, I'm tired. I misread `maintainers`, assuming it referred to me, not the _index maintainers_. I'm still going to reach out again to show good faith.

**Comment by Mr0grog** [comment]
Howdy! Are there any updates on this?

Barring that, is there a future where the top-level name of this package is changed to alleviate collisions? (Granted it is useful that you can install this in place of cchardet and magically make other packages that know nothing about it work, but it does make a lot of situations messy, as the OP noted.)

**Comment by wbarnha** [comment]
Sorry, there are no updates on this at the moment. I have not been able to allocate the time to work on this. :sweat:

**Comment by wbarnha** [comment]
Reached out to the original developer, haven't heard back.

**Comment by mike-clark-8192** [comment]
Could we use GitHub actions to automate the release of this package to PyPI under a second, separate namespace? That way people who are experiencing conflicts over `import cchardet` have the option to depend on / pip install `faust-faust_cchardet` and use it as `import faust_cchardet`? The primary namespace for this fork could still be `cchardet`, but people could access it via the auto-sync'd auto-published second package name to avoid the namespace overlap if they need/want that.
<details>
<summary>Incomplete GitHub Actions idea</summary>

```yaml
name: Publish to PyPI with Renamed Namespace
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with: { python-version: '3.x' }
    - name: Rename directory
      run: mv src/cchardet src/faust_cchardet
    - name: Update imports (if necessary)
      run: >-
        find . -type f -name '*.py' -exec
        sed -i 's/import cchardet/import faust_cchardet/g' {} +
    - name: Build the package
      run: python setup.py sdist bdist_wheel
    - name: Publish the package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
```

</details>
